executable = /nethome/ptasathish/projects/region-vlm-uncertainty/qwen_pipeline/scripts/run_probe_qwen_visual_forward.sh

request_CPUs = 4
request_memory = 64GB
request_disk = 120GB
request_GPUs = 1

requirements = (GPUs_GlobalMemoryMb >= 32000)
+MaxWallTime = 3600

output = /nethome/ptasathish/projects/region-vlm-uncertainty/qwen_pipeline/logs/probe_qwen_visual_forward.out
error  = /nethome/ptasathish/projects/region-vlm-uncertainty/qwen_pipeline/logs/probe_qwen_visual_forward.err
log    = /nethome/ptasathish/projects/region-vlm-uncertainty/qwen_pipeline/logs/probe_qwen_visual_forward.condor.log

queue
